# Site settings
title: "ModernNIC"
site: ""
description: > # this means to ignore newlines until "baseurl:"
    ModernNIC represents our take on a modern, user-controlled DNS system. We provide DNS recursion services,
    custom TLDs, and full peering with OpenNIC and ICANN.
baseurl: ""
paginate: 5
paginate_path: "/page:num/"
color:
    main: "accent-2 red"
    navbar: "accent-2 red"
    chips: "accent-2 red"
    footer: "accent-2 red"
owner:
    email: nic@moderntld.com
    facebook:
        show: false
        name: "Ichihara Rifa"
        url: "https://fb.me/nasya.aidan"
    github:
        show: true
        username: "ModernTLD"
    twitter:
        show: true
        username: "ModernTLD"
    disqus:
        show: true
        username: "jonaharagon"
sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
    - jekyll-paginate
